version: "3.3"
services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=1234567890
    ports:
      - "3307:3306"
    networks:
      - docker-network

  docker-java:
    depends_on:
      - mysqldb
    image: docker-java-service
    restart: unless-stopped
    container_name: docker-java-service
    build:
      context: ./DockerJavaService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/book_store?serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234567890",
        "spring.jpa.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    networks:
      - docker-network

  docker-python:
    image: docker-python-service
    container_name: docker-python-service
    build:
      context: ./DockerPythonService
      dockerfile: Dockerfile
    ports:
      - "8082:5000"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge